services:
  eureka-server:
    build: ../eurekaserver
    ports:
      - "8761:8761"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_ENDPOINT_URL=http://localstack:4566
      - JAVA_TOOL_OPTIONS=-Daws.endpointUrl=http://localstack:4566
    networks:
      - microservices-net

  api-gateway:
    build: ../apigateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_ENDPOINT_URL=http://localstack:4566
      - JAVA_TOOL_OPTIONS=-Daws.endpointUrl=http://localstack:4566
    networks:
      - microservices-net

  productservice:
    build: ../productservice
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_started
      mongodb:
        condition: service_started
      localstack:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/productos
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_ENDPOINT_URL=http://localstack:4566
      - JAVA_TOOL_OPTIONS=-Daws.endpointUrl=http://localstack:4566
    networks:
      - microservices-net

  orderservice:
    build: ../orderservice
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_started
      mongodb:
        condition: service_started
      localstack:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/ordenes
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_ENDPOINT_URL=http://localstack:4566
      - JAVA_TOOL_OPTIONS=-Daws.endpointUrl=http://localstack:4566
    networks:
      - microservices-net

  paymentservice:
    build: ../paymentservice
    ports:
      - "8083:8083"
    depends_on:
      eureka-server:
        condition: service_started
      mongodb:
        condition: service_started
      localstack:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/pagos
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_ENDPOINT_URL=http://localstack:4566
      - JAVA_TOOL_OPTIONS=-Daws.endpointUrl=http://localstack:4566
    networks:
      - microservices-net

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - microservices-net
    volumes:
      - mongodb_data:/data/db

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudwatch,logs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_DEFAULT_REGION=us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "./volume/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  mongodb_data:
